### ISSUE TITLE
Not clear in README that preScanModuleVerify depends on result from veracodePreScanResults

### ISSUE THREAD

**Issue by cspok82** [kctang/vt#5]
This causes confusion because i ran `preScanModuleVerify` without running `veracodePreScanResults`. `preScanModuleVerify` was showing errors that should not happen. Found out that it actually used the OLD `pre-scan-results.xml` file created in previous pre-scan for the verification.

It is not clear in README that `veracodePreScanResults` has to be executed before `preScanModuleVerify`.

Btw, should `preScanModuleVerify` rely on the result from `veracodePreScanResults`?

**Comment by kctang** [comment]
Noted that it is not in the README, will update when I get to it. I think it is ok for pSMV to rely on result of vPSR. However, pSMV should probably be smart enough to re-execute vPSR but that is not the case now.
