### ISSUE TITLE
about this plugin

### ISSUE THREAD

**Issue by asolomon15** [kctang/vt#7]
Hi, 

Has development for this plugin stopped ? Also does this work with gradle 2.4 ?

**Comment by kctang** [comment]
It has not been tested with Gradle 2.4 so I cannot confirm this. At the moment, there are no plans for further development on this plugin.

**Comment by asolomon15** [comment]
Thanks for responding.   Was there any reason why you discontinued developing this plugin ?

**Comment by kctang** [comment]
It is already doing its job of performing submission and generating reports in the environment that I use this tool. If Veracode changes its APIs and there is a need to update this tool, I might consider updating Gradle support for it.

You are definitely welcomed to fork and change it too. Let me know if you get stuck with specific issues doing that, I will try to help - if time permits.
