### ISSUE TITLE
Veracode API ID and Key support

### ISSUE THREAD

**Issue by tjarrettveracode** [kctang/vt#9]
Just a note that Veracode is deprecating username and password authentication for Veracode APIs. If this script is not updated to work with Veracode API ID and Key it will stop working once basic auth support is fully removed.

**Comment by tjarrettveracode** [comment]
For what it's worth, it looks like one of this project's forks has implemented ID and Key support: https://github.com/calgaryscientific/veracode-gradle-plugin

**Comment by kctang** [comment]
Thanks for sharing this. I do encourage using forks of this repo as I am no longer maintaining it.
